config/routes.rb
Rails.application.routes.draw do

 
 resources :circulations
 match 'vracanje' => 'circulations#vracanje', via: [:get, :post]
 
 resources :copies

 resources :items do
   collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
      get 'svi'
      get '/:id/povijest' => 'items#povijest', as: :povijest
      get 'inv_knjiga' => 'items#inv_knjiga', as: :inv_knjiga
      get 'posudjene'
      match 'fond' => 'items#knjiznifond', via: [:get, :post], as: :fond 
      match 'statistikapogod' => 'items#statistikapogod', via: [:get, :post], as: :statistikapogod 
      end
  end
 
 resources :users do
      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
        get 'svi'
        get '/:id/povijest' => 'users#povijest', as: :povijest
  end

end

  devise_for :admins

  devise_scope :admin do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
   end
  get "/static/st"
  get "/static/sa"
  get "/test" => "users#prazno"

 

end

app/models/copy.rb
class Copy < ActiveRecord::Base
 
 
 
  belongs_to :item
  has_many :circulations
  has_many :users, :through => :circulations
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  before_action :set_copy, only: [:show, :edit, :update, :destroy]
before_action :authenticate_admin!  

  # GET /copies
  # GET /copies.json
  def index
        @copies=Copy.all
  end

  # GET /copies/1
  # GET /copies/1.json
  def show
   
  end

  # GET /copies/new
  def new
    @copy = Copy.new
  end

  # GET /copies/1/edit
  def edit
  end

  # POST /copies
  # POST /copies.json
  def create
    @copy = Copy.new(copy_params)

    respond_to do |format|
      if @copy.save
        format.html { redirect_to @copy, notice: 'Copy was successfully created.' }
        format.json { render :show, status: :created, location: @copy }
      else
        format.html { render :new }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /copies/1
  # PATCH/PUT /copies/1.json
  def update
    respond_to do |format|
      if @copy.update(copy_params)
        format.html { redirect_to @copy, notice: 'Copy was successfully updated.' }
        format.json { render :show, status: :ok, location: @copy }
      else
        format.html { render :edit }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copies/1
  # DELETE /copies/1.json
  def destroy
    @copy.destroy
    respond_to do |format|
      format.html { redirect_to copies_url, notice: 'Copy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_copy
      @copy = Copy.find(params[:id])
    end
    
    

    # Never trust parameters from the scary internet, only allow the white list through.
    def copy_params
      params.require(:copy).permit(:barkod_knjige, :item_id)
    end
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/views/copies/_form.html.erb
<%= form_for(@copy) do |f| %>
  <% if @copy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@copy.errors.count, "error") %> prohibited this copy from being saved:</h2>

      <ul>
      <% @copy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :barkod_knjige %><br>
    <%= f.text_field :barkod_knjige %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.text_field :item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/copies/edit.html.erb
<h1>Editing Copy</h1>

<%= render 'form' %>

<%= link_to 'Show', @copy %> |
<%= link_to 'Back', copies_path %>

app/views/copies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Copies</h1>

<table>
  <thead>
    <tr>
      <th>Barkod knjige</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @copies.each do |copy| %>
      <tr>
        <td><%= copy.barkod_knjige %></td>
        <td><%= copy.item.naslov %></td>
        <td><%= link_to 'Show', copy %></td>
        <td><%= link_to 'Edit', edit_copy_path(copy) %></td>
        <td><%= link_to 'Destroy', copy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Copy', new_copy_path %>

app/views/copies/new.html.erb
<h1>New Copy</h1>

<%= render 'form' %>

<%= link_to 'Back', copies_path %>

app/views/copies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Barkod knjige:</strong>
  <%= @copy.barkod_knjige %>
</p>

<p>
  <strong>Item:</strong>
  <%= @copy.item %>
</p>

<%= link_to 'Edit', edit_copy_path(@copy) %> |
<%= link_to 'Back', copies_path %>