config/routes.rb
Rails.application.routes.draw do

 
 resources :circulations
 match 'vracanje' => 'circulations#vracanje', via: [:get, :post]
 
 resources :copies

 resources :items do
   collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
      get 'svi'
      get '/:id/povijest' => 'items#povijest', as: :povijest
      get 'inv_knjiga' => 'items#inv_knjiga', as: :inv_knjiga
      get 'posudjene'
      match 'fond' => 'items#knjiznifond', via: [:get, :post], as: :fond 
      match 'statistikapogod' => 'items#statistikapogod', via: [:get, :post], as: :statistikapogod 
      end
  end
 
 resources :users do
      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
        get 'svi'
        get '/:id/povijest' => 'users#povijest', as: :povijest
  end

end

  devise_for :admins

  devise_scope :admin do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
   end
  get "/static/st"
  get "/static/sa"
  get "/test" => "users#prazno"

 

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :circulations
    has_many :copies, :through => :circulations
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :authenticate_admin!
  # GET /users
  # GET /users.json
  def index
  if params[:q].blank?
    @q = User.none.search
    else
   @q = User.search(params[:q])
   
 end
    @users = @q.result.paginate(page: params[:page], :per_page => 10)
  end


def svi

   @users = User.paginate(page: params[:page], :per_page => 10)
end
  # GET /users/1
  # GET /users/1.json
  def show
  end
  
  def search
  index
  render :search
 
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def prazno
  end
  
  def povijest
     @user = User.find(params[:id])
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id, :ime, :prezime, :ulica, :grad, :PB, :email, :telefon1, :telefon2, :organizacija, :napomena)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
    def novi_barkod
        
        @nbarkod=User.last.id+1
        
    end
    
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label "Barkod" %><br>
    <%= f.text_field :id, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.label :ime %><br>
    <%= f.text_field :ime %>
  </div>
  <div class="field">
    <%= f.label :prezime %><br>
    <%= f.text_field :prezime %>
  </div>
  <div class="field">
    <%= f.label :ulica %><br>
    <%= f.text_field :ulica %>
  </div>
  <div class="field">
    <%= f.label :grad %><br>
    <%= f.text_field :grad %>
  </div>
  <div class="field">
    <%= f.label :PB %><br>
    <%= f.text_field :PB %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefon1 %><br>
    <%= f.text_field :telefon1 %>
  </div>
  <div class="field">
    <%= f.label :telefon2 %><br>
    <%= f.text_field :telefon2 %>
  </div>
  <div class="field">
    <%= f.label :organizacija %><br>
    <%= f.text_field :organizacija %>
  </div>
  <div class="field">
    <%= f.label :napomena %><br>
    <%= f.text_area :napomena %>
  </div>
  <div class="actions">
    <%= f.submit "Uredi korisnika", class: 'btn btn-success'%>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label "Barkod" %><br>
    <%= f.text_field :id, :value => @nbarkod, :autofocus => true %>
  </div>
  <div class="field">
    <%= f.label :ime %><br>
    <%= f.text_field :ime %>
  </div>
  <div class="field">
    <%= f.label :prezime %><br>
    <%= f.text_field :prezime %>
  </div>
  <div class="field">
    <%= f.label :ulica %><br>
    <%= f.text_field :ulica %>
  </div>
  <div class="field">
    <%= f.label :grad %><br>
    <%= f.text_field :grad %>
  </div>
  <div class="field">
    <%= f.label :PB %><br>
    <%= f.text_field :PB %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefon1 %><br>
    <%= f.text_field :telefon1 %>
  </div>
  <div class="field">
    <%= f.label :telefon2 %><br>
    <%= f.text_field :telefon2 %>
  </div>
  <div class="field">
    <%= f.label :organizacija %><br>
    <%= f.text_field :organizacija %>
  </div>
  <div class="field">
    <%= f.label :napomena %><br>
    <%= f.text_area :napomena %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_search.html.erb
<div class="row">
<div class="col-md-12 col-sm-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                         <h3>Pretraži korisnike </h3>
                        </div>
                        <div class="panel-body">
<br>

<%= search_form_for @q, url: users_path,
                        html: { method: :get } do |f| %>
  <div class="row">
  <div class="field col-md-3">
    <%= f.label :ime_cont, "Ime korisnika" %>
    <%= f.text_field :ime_cont, :autofocus => true %>
  </div>
  
  <div class="field col-md-3">
    <%= f.label :prezime_cont, "Prezime korisnika" %>
    <%= f.text_field :prezime_cont %>
  </div>
  <div class="field col-md-3">
    <%= f.label :id_eq, "Barkod korisnika" %>
    <%= f.text_field :id_eq %>
  </div>
  </div>
  <br>
  <div class="actions">
    <%=  f.submit  "Traži", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
<div class="col-md-12 col-sm-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                         <h3>Uredi korisnika </h3>
                        </div>
                        <div class="panel-body">

<%= render 'form' %>
</div>
</div>
</div>
</div>

<%= link_to 'Natrag na korisnika', @user %> |

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'search' %>
<br>
<% if !params[:q].blank? %>
<div class="panel panel-success">
                        <div class="panel-heading">
                            PRONAĐENI KORISNICI
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                
                                <table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Barkod</th>
      <th>Ime</th>
      <th>Prezime</th>
      <th>Ulica</th>
      <th>Grad</th>
      <th></th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.ime %></td>
        <td><%= user.prezime %></td>
        <td><%= user.ulica %></td>
        <td><%= user.grad %></td>
       
        <td><%= link_to 'Detalji', user %></td>
        <td><%= link_to 'Uredi', edit_user_path(user) %></td>
        <td><%= link_to 'Izbriši', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
                        </div>
                    </div>
                     
                      <%= will_paginate %> 
                </div>

<br>
<% end %>
<br>
</div>
</div>
</div>
</div>

app/views/users/new.html.erb
<div class="row">
<div class="col-md-12 col-sm-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                         <h3>Dodaj novog korisnika </h3>
                        </div>
                        <div class="panel-body">
<% novi_barkod %>
<%= render 'form_edit' %>

</div>
</div>
</div>
</div>

<%= link_to 'Natrag', users_path %>

app/views/users/povijest.html.erb
<div class="row">

    <div class="col-md-12 col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                   <h4>Povijest posudbe za "<%= @user.ime %> <%= @user.prezime %>"</h4>
            </div>
            <div class="panel-body">
                            
                 <table class="table ">
  <thead>
    <tr>
      <th>Naslov</th>
      <th>Barkod</th>
      <th>Posuđeno</th>
      <th>Vraćeno</th>
      
     
    </tr>
  </thead>
<tbody>
<tr>



 
 <% @user.circulations.each do |f| %>


 
 <td> <%= f.copy.item.naslov  %></td>
 <td> <%= f.copy.barkod_knjige  %></td>
 <td> <%= f.created_at.strftime("%d %m %Y")   %></td>
 <% if f.indikacija==2 %>
 <td> <%= f.updated_at.strftime("%d %m %Y")   %></td>
  <% else %>
  <td>-</td>
   <% end %>
  
  
  
</tr>
</tbody>
<% end %>



</table>
         
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<p class="notice" id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="panel panel-success">
                        <div class="panel-heading">
      <h1> <%= @user.ime %> <%= @user.prezime %> </h1>
      
      
      </div>
      </div>
    </div>
                <div class="col-md-6 col-sm-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                           <h4> Podaci o korisniku </h4>
                        </div>
                        <div class="panel-body">


<strong>Barkod:</strong>
  <%= @user.id %>
  <br>
<strong>Adresa:</strong>
  <%= @user.ulica %>, <%= @user.PB %> <%= @user.grad %>
  <br>

<strong>Email:</strong>
 <%= @user.email %>
  <br>
<strong>Telefoni:</strong> 
  <%= @user.telefon1 %>,  <%= @user.telefon2 %><br>
<strong>Organizacija:</strong> 
  <%= @user.organizacija %>
<br>
<strong>Napomena:</strong> 
  <%= @user.napomena %>
 </div>
      </div>
    </div>
    
    <div class="col-md-6 col-sm-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                           <h4> Trenutno posuđene knjige </h4>
                        </div>
                        <div class="panel-body">

<% if @user.circulations.posudjeno.count>0 %>
 <table class="table ">
  <thead>
    <tr>
      <th>Naslov</th>
      <th>Barkod</th>
      <th>Posuđeno</th>
      
      
     
    </tr>
  </thead>
<tbody>
<tr>



 
 <% @user.circulations.posudjeno.each do |f| %>


 
 <td> <%= link_to  f.copy.item.naslov, controller: "items", action: "show", id: f.copy.item.id %></td>
 <td> <%= f.copy.barkod_knjige  %></td>
 <td> <%= f.created_at.strftime("%d %m %Y")   %></td>

  
  
</tr>
</tbody>
<% end %>



</table>

<% else%>

NEMA POSUĐENIH KNJIGA!
<% end %>


 </div>
      </div>
    </div>
    
</div>
<%= link_to "<button>Posudi knjigu</button>".html_safe , controller: "circulations", action: "new", barko: @user.id %><br><br>
<%= link_to "<button>Prikaži povijest posuđivanja</button>".html_safe , povijest_users_path(@user) %><br><br>
<%= link_to 'Uredi', edit_user_path(@user) %> |
<%= link_to 'Natrag', svi_users_path %>

app/views/users/svi.html.erb
<p id="notice"><%= notice %></p>

               
            <div class="row">
                <div class="col-md-12 col-sm-12">
                   <!--   Kitchen Sink -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            POPIS KORISNIKA
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                
                                <table class="table table-striped table-bordered table-hover">





  <thead>
    <tr>
      <th>Barkod</th>
      <th>Ime</th>
     
      <th>Ulica</th>
      <th>Grad</th>
      <th></th>
      <th></th>
      <th></th>
      
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
         <td><%= user.id %></td>
        <td><%= user.ime %> <%= user.prezime %></td>
       
        <td><%= user.ulica %></td>
        <td><%= user.grad %></td>
    
        <td><%= link_to 'Detalji', user %></td>
        <td><%= link_to 'Uredi', edit_user_path(user) %></td>
        <td><%= link_to 'Izbriši', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
 
</table>

<br>

</div>
                        </div>
                    </div>
                     <!-- End  Kitchen Sink -->
                        <%= will_paginate @users %> 
                </div>
            </div>