config/routes.rb
Rails.application.routes.draw do

 
 resources :circulations
 match 'vracanje' => 'circulations#vracanje', via: [:get, :post]
 
 resources :copies

 resources :items do
   collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
      get 'svi'
      get '/:id/povijest' => 'items#povijest', as: :povijest
      get 'inv_knjiga' => 'items#inv_knjiga', as: :inv_knjiga
      get 'posudjene'
      match 'fond' => 'items#knjiznifond', via: [:get, :post], as: :fond 
      match 'statistikapogod' => 'items#statistikapogod', via: [:get, :post], as: :statistikapogod 
      end
  end
 
 resources :users do
      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
        get 'svi'
        get '/:id/povijest' => 'users#povijest', as: :povijest
  end

end

  devise_for :admins

  devise_scope :admin do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
   end
  get "/static/st"
  get "/static/sa"
  get "/test" => "users#prazno"

 

end

app/views/layouts/staro/_footer_stari.html.erb
dfsfs

app/views/layouts/staro/_header_stari.html.erb
<div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
    <div class="container-fluid">
        <div class="navbar-header"><a class="navbar-brand" href="#">Brand</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul id="navigacija" class="nav navbar-nav navbar-left">
  <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
          aria-haspopup="true" aria-expanded="false">Knjige <span class="caret"></span></a>
         <ul class="dropdown-menu">
            <li><%= link_to "Pretraga knjiga", items_path%></li>
            <li><%= link_to "Dodaj novu knjigu", new_item_path%></li>
            <li><%= link_to "Knjige", svi_items_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
 <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
          aria-haspopup="true" aria-expanded="false">Korisnici <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Pretraga korisnika", users_path%></li>
            <li><%= link_to "Dodaj novog korisnika", new_user_path%></li>
            <li><%= link_to "Korisnici", svi_users_path%></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
          aria-haspopup="true" aria-expanded="false">Cirkulacija <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Posudi knjigu", new_circulation_path%></li>
            <li><%= link_to "Vraćanje knjige", vracanje_path%></li>
          </ul>
        </li>
        <li><a href="#">Inventarna knjiga</a>
        <li><a href="#">Statistika</a>
                </li>
                <!--<li class="<%= "active" if current_page?(static_st_path) %>"> <%= link_to "Statična", static_st_path%>-->
                <!--</li>-->
                <!--<li class="<%= "active" if current_page?(static_sa_path) %>"><%= link_to "About", static_sa_path%>-->
                <!--</li>-->
                
            </ul>
            <ul id="navigacija" class="nav navbar-nav navbar-right">
               
                
                <% if admin_signed_in? %>
                <li><%= link_to "Odjava", logout_path%>
                </li>
                <% else %>
                <li> <%= link_to "Prijava", login_path%>
                </li>
                <% end %>
                </li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/staro/application_stari.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pdk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
   <%- if controller_name != 'sessions' %>
   
   <%= render 'layouts/header' %>
   <% end -%>
   <div>
      <p class="alert-success"><%= notice %></p>
      <p class="alert-danger"><%= alert %></p>
      </div>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>