config/routes.rb
Rails.application.routes.draw do

 
 resources :circulations
 match 'vracanje' => 'circulations#vracanje', via: [:get, :post]
 
 resources :copies

 resources :items do
   collection do
      match 'search' => 'items#search', via: [:get, :post], as: :search
      get 'svi'
      get '/:id/povijest' => 'items#povijest', as: :povijest
      get 'inv_knjiga' => 'items#inv_knjiga', as: :inv_knjiga
      get 'posudjene'
      match 'fond' => 'items#knjiznifond', via: [:get, :post], as: :fond 
      match 'statistikapogod' => 'items#statistikapogod', via: [:get, :post], as: :statistikapogod 
      end
  end
 
 resources :users do
      collection do
        match 'search' => 'users#search', via: [:get, :post], as: :search
        get 'svi'
        get '/:id/povijest' => 'users#povijest', as: :povijest
  end

end

  devise_for :admins

  devise_scope :admin do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
   end
  get "/static/st"
  get "/static/sa"
  get "/test" => "users#prazno"

 

end

app/views/layouts/_footer.html.erb
</div>
               
    </div>
             <!-- /. PAGE INNER  -->
            </div>
         <!-- /. PAGE WRAPPER  -->
     <!-- /. WRAPPER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <!--<script src="assets/js/jquery-1.10.2.js" data-no-turbolink></script>-->
      <!-- BOOTSTRAP SCRIPTS -->
    <!--<script src="assets/js/bootstrap.min.js" data-no-turbolink></script>-->
    <!-- METISMENU SCRIPTS -->
   
     <!-- DATA TABLE SCRIPTS -->
  
       
      
       
       
       
       
       
         <!-- CUSTOM SCRIPTS -->

app/views/layouts/_header.html.erb
 <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href=<%= static_st_path %>>
                    
                    <% if !current_admin.nil? && !current_admin.prezime.nil? %>
                    <%= current_admin.ime %> <%= current_admin.prezime %></a> 
                    <% end %>
                    </a> 
            </div>
            <div style="color: white;
padding: 15px 50px 5px 50px;
float: left;
font-size: 20px;"> PRVA DJEČJA KNJIŽNICA ZA DJECU S OŠTEĆENJEM VIDA</div>
  <div style="color: white;
padding: 15px 50px 5px 50px;
float: right;
font-size: 16px;"><a href=<%=logout_path%> class="btn btn-danger square-btn-adjust">Logout</a></div>
        </nav>  
        

app/views/layouts/_sidebar.html.erb
 <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
				<li class="text-center">
                   
                    <img src=<%= image_url "find_user.png" %> class="user-image img-responsive"/>
					</li>
				
					
					                   
                    <li>
                        <a href="#"><i class="fa fa-book fa-3x"></i> Knjige<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                             <li><%= link_to "Pretraga knjiga", items_path%></li>
                            <li><%= link_to "Dodaj novu knjigu", new_item_path%></li>
                          <li><%= link_to "Knjige", svi_items_path %></li>
                        </ul>
                      </li>  
                      <li>
                        <a href="#"><i class="fa fa-user fa-3x"></i> Korisnici<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                           <li><%= link_to "Pretraga korisnika", users_path%></li>
                            <li><%= link_to "Dodaj novog korisnika", new_user_path%></li>
                            <li><%= link_to "Korisnici", svi_users_path%></li>
                           
                        </ul>
                      </li>  
                  <li>
                        <a href="#"><i class="fa fa-barcode fa-3x"></i> Cirkulacija<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li><%= link_to "Posudi knjigu", new_circulation_path %></li>
                            <li><%= link_to "Vraćanje knjige", vracanje_path %></li>
                            
                        </ul>
                      </li>  



                        <li>
                       
                         <%= link_to ('<i class="fa fa-pencil-square fa-3x"></i> Inventarna knjiga').html_safe, inv_knjiga_items_path(params.merge(:format => "pdf")) %>
                         
                         </li>
                        <li>
                        <a   href="#"><i class="fa fa-bar-chart-o fa-3x"></i> Statistika<span class="fa arrow"></span></a>
                           <ul class="nav nav-second-level">
                            <li><%= link_to "Posuđene stavke", posudjene_items_path %></li>
                           <li><%= link_to "Trenutno stanje fonda", fond_items_path %></li>
                            <li><%= link_to "Statistika fonda po godinama", statistikapogod_items_path %></li>
                        </ul>
                    </li>	
                </ul>
               
            </div>
            
        </nav>  
        <!-- /. NAV SIDE  -->
        <div id="page-wrapper" >
            <div id="page-inner">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PDK</title>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- BOOTSTRAP STYLES-->
   <!-- <link href="assets/css/bootstrap.css" rel="stylesheet" />-->
     <!-- FONTAWESOME STYLES-->
   <!-- <link href="assets/css/font-awesome.css" rel="stylesheet" />-->
     <!-- MORRIS CHART STYLES-->
   
        <!-- CUSTOM STYLES-->
   <!-- <link href="assets/css/custom.css" rel="stylesheet" />-->
     <!-- GOOGLE FONTS-->
   <!--<link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />-->
     <!-- TABLE STYLES-->
   <!-- <link href="assets/js/dataTables/dataTables.bootstrap.css" rel="stylesheet" />-->
</head>
<body>
     <%- if controller_name != 'sessions' %>
   
   <%= render 'layouts/header' %>
   <%= render 'layouts/sidebar' %>

  
   <% end -%>
   
<%= yield %>

<%= render 'layouts/footer' %>



<%= debug(params) if Rails.env.development? %>
</body>
</html>